### PR TITLE
Elm v0.19.0 support + minor fixes

### PR DESCRIPTION
**Pull request by vViktorPL**
I've added support for Elm v0.19.0 and some minor fixes for markdown formatting and type docs when type constructor is not exposed in the module.

### CODE REVIEW

**Comment by baransu** [comment]
Amazing work, thank you! 🎉 Please remove version bump from PR. It will be handled during `npm publish` 🙂

**Comment by vViktorPL** [comment]
Done :)

**Comment by baransu** [comment]
Thank you! I’ll try to release it today :)

**Comment by baransu** [comment]
Released as `0.4.0` 🎉

**Pull request merged**
